### ISSUE TITLE
Adding Iterator / generator type 

### ISSUE THREAD

**Issue by aria1th** [gnembon/scarpet#104]
We can definitely use loop or nested loop, but it makes code much hard to read, and it is not reusable. 
Iterator provided in scarpet is block iterator, which directly accesses to the block, not the coordinate list, such as example:

/script run for(diamond(0,0,0,1,1),print(_))
[15:11:59] [main/INFO]: [CHAT] void_air
[15:11:59] [main/INFO]: [CHAT] white_concrete
[15:11:59] [main/INFO]: [CHAT] white_concrete
[15:11:59] [main/INFO]: [CHAT] black_concrete
[15:11:59] [main/INFO]: [CHAT] black_concrete
[15:11:59] [main/INFO]: [CHAT] white_concrete
[15:11:59] [main/INFO]: [CHAT] air

So, using it would actually load the coordinates.

I made coordinate iterator, which would not load or access it, but just return the list of the coordinates such as

rect_iter(origin, dist) ->
(
	l(x,z) = origin;
	dist = abs(dist);
	res = l();
	l(xmin, xmax) = l(x-dist, x+dist+1);
	l(zmin, zmax) = l(z-dist, z+dist+1);
	c_for(ax=xmin, ax<xmax, ax+=1,
		c_for(az=zmin, az< zmax, az+=1,
			res+=l(16*ax, 16*az)
		)
	);
	return(res)
);

which would point out one points per chunk. But it is RAM consuming, of course, cause it stores all the coordinates possible, not returning one at a time.

Can you add control flow function such as yield()? I tried making independent module for it, but since access to memory address is not allowed, I had to make own rng to store and access it.

**Comment by Ghoulboy78** [comment]
you can do this:
```
for(diamond(0,0,0,1,1),
    pos(_)
)
```
That makes this sorta pointless

**Comment by Ghoulboy78** [comment]
and for rectangles you do `for(rect(bla,bla,bla), do whatever)`

**Comment by aria1th** [comment]
Oh, I actually thought _ itself contains loading the point. Thank you
