### ISSUE TITLE
[suggestion]Add collection/tuple unpacking to scarpet

### ISSUE THREAD

**Issue by psychothermal-whale** [gnembon/scarpet#107]
If you have a collection `L` you can unpack it in Python with `*L` or in JavaScript with `...L`. Basically, `f(*L) <=> f(L[0], L[1], L[2], ..., L[-1])`. This comes in useful in many cases with scarpet, e.g.:
`inventory_get(p)` -> 1 arg for inventory
`inventory_get('enderchest', p)` -> 2 args for inventory

In order to cycle through the inventory of the player and their ender chest, there is no simple solution like `for (l(l(p), l('enderchest', p)), inventory_get(..._))`; in fact, there is no way to do it but to write everything twice, once with `inventory_get(p)` and another time with `inventory_get(p, 'enderchest')`.

There are 2 possible solutions I can think of:
1. Add an operator that does this, like the Python `*` or the JS `...`, which is probably more work
2. Add a function that does this, like the Clojure `apply`, where `apply(function, collection) <=> function(collection[0], collection[1], collection[2], ..., collection[-1])`, which is probably less work.

Right now I'm using something that in practise does the same as `apply` but it's very evil and should never be done...
```
apply(f, l) -> run('script run '+f+'('+replace(''+l, '[\\[\\]]', '')+')')
```
Yes, `f` is a string. It's the function name, like you would pass it to `schedule()`. It's ugly.

**Comment by gnembon** [comment]
tuple unpacker is a tough call, since its a weird syntactic flex from some languages, and parser that scarpet uses doesn't support it. Most functions that accept multiple arguments can accept them as a list as well for more programmatic way to call them
