### ISSUE TITLE
eval() - execute string contents.

### ISSUE THREAD

**Issue by bwucke** [gnembon/scarpet#11]
eval() gives every scripting language a lot of power - ability to construct scripts, get them from unusual inputs and store in unusual ways. Examples: text of a written book. Items with custom behaviors encoded in the item metadata, input from external plugins e.g. discord chat, and so on. It's also probably the easiest way to implement lambda expressions, especially if paired with means to extract function source as a string.

**Comment by encloinc** [comment]
an eval statement would be amazing!

**Comment by gnembon** [comment]
lets assume we have some code written in a book. What would make it execute that code? some player action?
I am asking because with commandblocks its easy - pressing a button on a commandblock is essentially doing .eval() on it. How this would work on a book for example.

**Comment by bwucke** [comment]
A command block still, or whatever other 'code execution environment', a chat window command, etc, wherever the eval() is used - it would be just another function. Using a command block would require a tiny snippet of code selecting the container of the command text (e.g. the book), and potentially condition when to execute, like place in a named item frame or in the off-hand (unless the command block triggers on a button press / redstone input), then pass the extracted code to eval. 

And yes, pressing a button on a command block is essentially doing .eval() _on it_ - that's why I believe the functionality should be pretty easy to implement, simply expose that very call to general scripting with the input parameter being the function's parameter instead of that one specific block entity data field. 

I'm even fairly sure one could even cheese it currently as a function in carpet script that saves a block in the world, summons a command block in its place setting its command to the function's parameter, activates the command block, then despawns it and restores the block it had replaced. A little messy with all that unnecessary block spawning and despawning but it would work. Doing it elegantly through a proper call without spawning unnecessary stuff into the world would be the big contribution of eval().

**Comment by PegasusEpsilon** [comment]
`/script run run('script run ' + evaluated_string)`
