### ISSUE TITLE
How can I get the cam.sc script to work?

### ISSUE THREAD

**Issue by FlashHUN** [gnembon/scarpet#116]
I put it in the scripts folder inside the world folder and enabled script autoloading. I can't figure out how to use it though. Do I need to change something inside the script? The console says that it removes the script as soon as the server starts up, but why?

**Comment by altrisi** [comment]
Oh, that's interesting.
To solve it, add the following code at the top of the script, and it should work:
```py
__config() -> (m(
  l('stay_loaded','true')
));
```
Basically it configures it to not be unloaded after server load.
I'll create a PR to solve this in the repo.

**Comment by FlashHUN** [comment]
Thank you!
