### ISSUE TITLE
[Question] Testing whether a log is part of a tree

### ISSUE THREAD

**Issue by kyroschow** [gnembon/scarpet#117]
Looking at the veinminer script, I want to contribute to making a treecapitator script.
But I'm not sure what the best way to test whether a log is part of a tree (and not a player placed log).
Currently I'm thinking to check whether the bottom log is above a dirt block and its adjacent logs are connected to the tree.
Any suggestions?

**Comment by KrisCris** [comment]
Actually those naturally generated leaves have a variable `PERSISTENT` indicating whether the leaf was placed manually.
`public class LeavesBlock extends Block {   public static final BooleanProperty PERSISTENT; }`

I am not sure whether we could get that information, but if we can then we could know whether a log is part of the tree.

**Comment by Firigion** [comment]
Yes, you can get that information with `property(block)`. How to use it is the hard part.

**Comment by KrisCris** [comment]
I don't know. What about scanning from bottom to top, then destroy these blocks reversely... Like pushing all the pos into a stack by some rules, if 100% sure it is a tree, i.e. no illegal blocks adjacent to it and all the blocks are just leaves and logs, then cut it.

**Comment by gnembon** [comment]
I tried to do treecapitator that does work with all vanilla tree types and only chops one tree at a time, and doesn't chop other logs that may not belong to that tree even touching it. With mixed results.

**Comment by Ghoulboy78** [comment]
See BisUmTo's treecapitator script for RedCraft: https://github.com/MultiCoreNetwork/carpet-redcraft-addons/blob/master/src/main/resources/assets/carpet-redcraft-addons/scripts/treecapitator.sc
