### ISSUE TITLE
Auto lighter won't light up the surface?

### ISSUE THREAD

**Issue by KrisCris** [gnembon/scarpet#124]

**Comment by PMX-Universe** [comment]
As far as I know it was never designed to do that.

**Comment by KrisCris** [comment]
After checked the code, I believe you are right.

I am just wondering if I could enable this by slightly modifying the code since I am not familiar with the language used. And I think perhaps this behavior is related to the if-statement from line 38 to 40 `if (__distance_sq(cpos, lpos) <= 16384  
					&& air(lpos) && light(lpos) < 8 && sky_light(lpos) < 8
					&& solid(pos_offset(lpos, 'down')),`

I tried to remove `&& sky_light(lpos) < 8`, but it didn't work...

**Comment by PMX-Universe** [comment]
It seems that the function licht always returns 15 for every place that has no block above it (Direct sky light and even in the night.). You could remove that part but that will result in way more torches than needed. To be precise it will fill all avaible spaces with torches...

**Comment by PMX-Universe** [comment]
The solution to this is change to that function `light(lpos)` to `block_light(lpos)` and remove the part `&& sky_light(lpos) <8`.

**Comment by KrisCris** [comment]
> The solution to this is to change that function `light(lpos)` to `block_light(lpos)` and remove the part `&& sky_light(lpos) <8`.

Thanks a lot!

I didn't realize that there's a different method for the light... I should have a look at the API first. XD
