### ISSUE TITLE
world_map.sc throws concurrentModificationException after the first loading

### ISSUE THREAD

**Issue by KrisCris** [gnembon/scarpet#125]
GameVersion: 1.16.1

<img width="655" alt="Screen Shot 2020-08-02 at 12 04 49 PM" src="https://user-images.githubusercontent.com/38860226/89115234-9c535780-d4b8-11ea-88e6-2e21390760f3.png">

**Comment by gnembon** [comment]
I believe that was fixed, might be wrong though
