### ISSUE TITLE
cam.sc does not save player's dimension

### ISSUE THREAD

**Issue by CrazyHPi** [gnembon/scarpet#127]
e.g. player1 uses `/cam` switch to spectator in overworld and there is a player2 in nether, then player1 uses spectator teleport to player2 and uses `/cam` again to switch back to survival. This results player1 being placed in nether with overworld coordinate. 

btw I didn't see how to change player's dimension in docs, maybe add one or use `/execute in <diemension> ` ?

**Comment by ScottBall594** [comment]
https://github.com/gnembon/scarpet/pull/122
