### ISSUE TITLE
'Script scan setbiome' command doesn't work.

### ISSUE THREAD

**Issue by Megaminx12** [gnembon/scarpet#129]
If I type /script scan 311 5 19 311 5 19 321 10 21 set_biome(_, 'warm_ocean') it says the scan was successful but the biome in f3 is the same as it was before. Worked fine in 1.16.1.

Edit: I tested it with a snowy taiga biome and a normal taiga biome, and it worked, so the issue is specifically an issue with warm ocean.

**Comment by gnembon** [comment]
overworld biomes are flat, meaning, you need to set it for Y=0 block. Only 3D biome dimensions you set it per coordinate.
