### ISSUE TITLE
cam.sc feature request: Adding a noclip option to prevent players from seeing inside of builds.

### ISSUE THREAD

**Issue by Greg-J** [gnembon/scarpet#135]
We like to use the cam feature to allow players to take screenshots, but we'd like to prevent players from clipping through solid blocks.

Being able to disable teleport would be nice too.

**Comment by Ghoulboy78** [comment]
wdym clipping through and teleporting?

**Comment by Greg-J** [comment]
> wdym clipping through and teleporting?

Looking through the code I can see that this script effectively sets you in spectator mode and gives you some status effects. Spectator mode allows you to noclip. So on a survival server, this allows you to see through peoples bases, storage systems, etc.

What I'm looking at is, can we perform a check while they're in spectator mode that looks at the block their head is in and if it's not air or water, teleport them them on block behind them - or something like that. Effectively preventing them from moving through solid blocks.

As for teleporting, it would be nice if we could disable the ability to teleport to a player using the menu to prevent spying eyes.

Am I explaining this well enough?

**Comment by Ghoulboy78** [comment]
yeah, I just wanted to confirm thats what you meant.

**Comment by Ghoulboy78** [comment]
Ig I could do, but later in the weekend cos super busy rn

**Comment by Greg-J** [comment]
That's awesome. You rock!

**Comment by Greg-J** [comment]
@Ghoulboy78, anything ever come of this?

**Comment by Ghoulboy78** [comment]
sry mate, just been hella busy lately

**Comment by gnembon** [comment]
that defies the purpose of the camera app.

**Comment by Greg-J** [comment]
@gnembon you don't see the value in allowing freecam but preventing users from clipping?
