### ISSUE TITLE
Signs_for_water_streams does not update water when sign is placed.

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [gnembon/scarpet#140]
#130 Previously I got an error message when I ran the script. I fixed it after i opened an issue. I also updated it for the new 1.16 wood types. Now I'm getting a new error where the water is not updated. Screenshot attached. Updated 1.16 + error message script attached.

DISCLAIMER: I don't know scarpet. I just added the wood types at the start in quotation marks like the other wood types, and I just followed instructions others gave me.
[signs_for_water_streams.zip](https://github.com/gnembon/scarpet/files/5307500/signs_for_water_streams.zip)
![2020-09-30_19 16 52](https://user-images.githubusercontent.com/68545280/94724337-0b7ee800-0352-11eb-9fcf-73b605e5dc39.png)

**Comment by Megaminx12** [comment]
I had to do a .zip for the script because github can't support .sc

**Comment by Ghoulboy78** [comment]
.sc is text, so you can just copy pasta code...

**Comment by Ghoulboy78** [comment]
You basically had a bunch of syntax errors, so Imma just send the fixed verions and it should work.

**Comment by Megaminx12** [comment]
thx
I'll close the issue once you send it.

**Comment by Ghoulboy78** [comment]
```
// signs_for_water_streams by indoorjetpacks

// Sneak click while placing signs to place it without getting the 'Edit sign message' prompt. Sneak click already skips GUI/interactions for other blocks, why not signs also? Makes sense to me.

// Useful for placing water/lava flows if you make a lot of them. Lookin' at you, SciCraft server.



//written for scarpet 1.6 in carpet mod 1.3.0. Both from the amazing gnembon (although...how'd you get this far without knowing that?)

//https://github.com/gnembon/fabric-carpet/releases



__config() ->

(

	m(

		l('stay_loaded', true),

		l('scope', 'global')

		)

);



// namespaces for items and placed signs differ, so map each wall_sign to it's item equivalent

global_item_to_block = {
	'acacia_sign'-> 'acacia_wall_sign',
	'birch_sign'-> 'birch_wall_sign',
	'dark_oak_sign'-> 'dark_oak_wall_sign',
	'jungle_sign'-> 'jungle_wall_sign',
	'oak_sign'-> 'oak_wall_sign',
	'spruce_sign'-> 'spruce_wall_sign',
	'crimson_sign'-> 'crimson_wall_sign',
	'warped_sign'-> 'warped_wall_sign'
};

__on_player_right_clicks_block(player, item_tuple, hand, block, face, hitvec) ->(
	if(//check if player has a sign item + convert it to the wall placed ID name for the set(), check if player sneaks, and make sure the block isn't a storage block

		block_to_place = global_item_to_block:(item_tuple:0) && player ~ 'sneaking' && inventory_size(pos(block))==null &&
		
		face != 'up' && face != 'down', //make sure the player clicked on the side of a block, not the top or looking upward.

		offset_by_one =block( pos_offset(block,face));

		//without the offset, the block you clicked on will be turned into a sign.

		//make sure there's a replaceable block there, otherwise you could auto-destroy blocks with this.

		replaceable_materials = ['air', 'water', 'lava', 'grass','sea_grass'];

		if( replaceable_materials~offset_by_one,

			set(offset_by_one, block_to_place, 'facing', face);
			//Un-comment this line if you still see no updates: block_update(offset_by_one)
		)
	)
)
```

**Comment by Megaminx12** [comment]
Got an error saying bracket not closed, I closed it. I then got an error saying that 'block_update' is not defined (I uncommmented it after it didn't update at first.

**Comment by Ghoulboy78** [comment]
ah wait the function is update() not block_update()

**Comment by indoorjetpacks** [comment]
been meaning to check this over again since there's been an scarpet update since i wrote it, and we're in 1.16 now so new sign blocks as you mentioned megaminx. i should be able to take a look in a few hours after im done with work unless one of yall fixes it first. feel free to submit a pull request if so :D

**Comment by Ghoulboy78** [comment]
yeah, chill dude, im doing it, dont worry

**Comment by Ghoulboy78** [comment]
@Megaminx12 It's fixed

**Comment by Megaminx12** [comment]
thx

**Comment by Megaminx12** [comment]
where can I find the code

**Comment by Megaminx12** [comment]
@Ghoulboy78

**Comment by Meeni-mc** [comment]
As far as I can tell, Vanilla is the same.
