### ISSUE TITLE
shulkerboxes.sc Error

### ISSUE THREAD

**Issue by jseaz73** [gnembon/scarpet#143]
Love this mod!  it is a much-needed part of the game. 

I turned on shulkerboxes.sc.  

I have a box called "Sand vacuum"  and  "Builder swap same"  they were dyed?  IDK if that would hurt this 

I was testing the swap and hit this error  In addition, the vacuum was not working ..   Had sand and dirt "seeded" in the shulker

![shulkererror](https://user-images.githubusercontent.com/16529812/95579865-5fe62f80-0a04-11eb-9979-d9655a2d81f2.png)

**Comment by samolego** [comment]
I can confirm the vacuum not working, regardless of the color.

**Comment by gnembon** [comment]
you are probably working with an older version of carpet
Please update to at least a version that came out when shulkerboxes app showed up.
