### ISSUE TITLE
Inserting scarpet scripts into a datapack to run from the game. [add Support to load scripts from disk]

### ISSUE THREAD

**Issue by FlipKING78** [gnembon/scarpet#17]
It's stated that it should be possible to use a datapack to store scripts instead of typing them in a commandblock or chat.
But it's never mentioned how it's done.
So I'm asking how to do it and if it isn't possible are there any other ways to do it ?

**Comment by gnembon** [comment]
/script run is just a command. datapacks contain mcfunctions, which are just lists of commands, therefore it would be possible to add them as part of the datapacks.

Having said that - it might still be an issue the lack of proper newline support so having an options to have a bunch of *.sc files with a world or a datapack loadable with /script load might be a good idea.

**Comment by gnembon** [comment]
Note to self - let all loaded libraries run in their own script hosts - not affecting other libraries, or user functions called from commandline

**Comment by gnembon** [comment]
merged in ability to load modules from /scripts/xxxx.sc files in world files.
