### ISSUE TITLE
[suggestion] add mob damage function

### ISSUE THREAD

**Issue by zane49er2** [gnembon/scarpet#179]
There is currently no way to easily simulate the entire mob damage process, including turning the mob red, dealing knockback, and crediting a player for the purposes of advancements/scoreboards/death messages/enchantments. I reccomend this be changed with a function that looks something like
hit_entity(entity_hit, damage, entity_attacker?, knockback_direction)

**Comment by replaceitem** [comment]
Partially duplicate to [fabric-carpet#649](https://github.com/gnembon/fabric-carpet/discussions/649) which uses `modify()` instead. However the knockback direction is new and could be added to that too.

**Comment by Ghoulboy78** [comment]
this would be better suited as an expansion to the scarpet language, so a pr to fabric-carpet
