### ISSUE TITLE
cam.sc does not teleport back to correct dimension on a server

### ISSUE THREAD

**Issue by TheCatSaber** [gnembon/scarpet#180]
How to reproduce:

Install cam.sc on a server. (Issue did not occur on singleplayer).

Go into survival.

Run `/cam`.

Run `/execute in minecraft:the_nether tp @p 0 128 0` to teleport to the nether.

Run `/cam` again.

You should now come back out in the nether.

**Comment by TheCatSaber** [comment]
My interim measure to to replace lines 36-38 with this, to make it the player's issue.
```
         // Only make survival if in same dimension
         if (p~'dimension'==config:'dimension',
            __remove_camera_effects(p);
            __restore_player_params(p, config);
            __remove_player_config(p~'name'),
            // Otherwise say wrong dimension
            p~'dimension'!='dimension',
            print('You must be in the same dimension you took off in: '+config:'dimension'+'.')
         )
```

**Comment by Ghoulboy78** [comment]
hmm, true. Thought it had been fixed...

**Comment by altrisi** [comment]
Oh, only on a server. That's why I couldn't reproduce it.

**Comment by altrisi** [comment]
Nope, still can't reproduce, works for me. Are you for any chance running Carpet TIS Addition with `opPlayerNoCheat` rule?

The cam app currently relies on using the `tp` vanilla command to change dimensions (since it's not yet supported natively in Scarpet, I'm in the process of adding it), and that rule blocks Scarpet from running the command.

**Comment by TheCatSaber** [comment]
I am not running the opPlayerNoCheat, and I am unsure why it won't work, given the command console can still do ```/execute in minecraft:dimension run tp player ~ ~ ~```, and it works correctly. I intend to see if changing the command to tping to 0 128 0 works when I get the chance. I also noticed at least 1 other person had this issue on scicraft discord recently.

**Comment by altrisi** [comment]
Hm... Maybe try changing the `commandScriptACE` rule to a higher value, though it should already be 2 ( == `ops`, min permission to run `tp`) by default. That's the only way I've been able to not tp out of the nether.

**Comment by TheCatSaber** [comment]
Solved: The carpet.conf started with #locked, overriding the commandScriptACE, therefore you have to set commandScriptACE equal to 2 in carpet.conf. Will make a PR to put in comments of cam.sc, the readme, and also edit the fabric-carpet wiki.

**Comment by altrisi** [comment]
I'll keep this open while one of the fixes is done, so others can see the workaround.
