### ISSUE TITLE
#182 removed some commits from the Signs for water streams app

### ISSUE THREAD

**Issue by altrisi** [gnembon/scarpet#184]
When making and reviewing #182, no one noticed the fix was based on a previous version of the app, therefore letting commits a07f7f391804a033da60bde4b6d402af07fda55e and f1da9ea3961566b3318e0925f15972e75a143f6e outside of the current app.

Most notably, that removed the heuristics that made the app work with modded signs. It also removed a dupe fix when placing signs from offhand and a QOL for placing in creative without using items (not really tested those last ones though).

Why I think it was based on the old version (probably 3e0b0ebe5c0d93cfc833add96789902d40adc4be):

Scarpet version was dropped down, when it went up in those commits: https://github.com/gnembon/scarpet/commit/38ff8c574eb0ee7abb87b2bff7410bdbdb32c284#diff-8bb66dc9e8f062b283436ed4626c5d88f606d4ce010de8c2c3a7fdf09d8d59f7R6-R8

Also the line specifying the update is also gone, plus some of the old formatting is back.

Pointed out by the author of those commits in https://github.com/gnembon/scarpet/pull/182#issuecomment-780252775.

**Comment by Ghoulboy78** [comment]
oops...
