### ISSUE TITLE
get(block, "Items[]") sometime is a list, sometime is a scalar

### ISSUE THREAD

**Issue by Meeni-mc** [gnembon/scarpet#185]
## The problem

Look at this snippet:

```it=get(bd=block_data(b), 'Items[]'))```

Dependent upon how many items are in the block tile, the following code will return either 
1. `null`,
2. `[{item1...},{item2...}]`
3. `{item1}`

This is annoying, because the result cannot be passed to `map()`, `filter()` and so on directly, without doing some extra fluff code to check type and retype. 

The `null` is reasonable, however, the case 3: `{item1}` is questionable. 

### Make `get(b, 'Items[]')` always return a list, even if it's a 1-item list. 

This is in my opinion the correct behavior and the correct bugfix.

I have been told that this behavior of demoting 1-item lists to scalars is inherited from Vanilla `data` queries. Still this appears inconsistent/puzzling/annoying. 

---

### Make `map` and similar functions accept scalars as input

```map({item1}, ...)``` would then be equivalent to ```map([{item1}], ...)```. There is some concerns regarding loosening the typing of the language. I don't think type checking is critical in Scarpet, but one may think otherwise and make a convincing argument. 

---

### Do nothing 

With no changes to Scarpet, the case can be handled with the following snippet:

```if(null != (it=get(bd=block_data(b), 'Items[]')), if(!has(it, 0), it=l(it)); map(it, ...)```
 (I have been told that `type()` could also work here). 

It is not nice or logical, but it works just fine.

**Comment by altrisi** [comment]
I think this issue would be better suited to gnembon/fabric-carpet, since this repo's issues are more about the apps in here, not actual language suggestions/bugs (based on some that have been moved in the past).

**Comment by gnembon** [comment]
yeah, would move normally, but will close since its already duplicated
