### ISSUE TITLE
Add proper datapack support (not just world folder scripts)

### ISSUE THREAD

**Issue by xMGZx** [gnembon/scarpet#193]
This is a request related to #17. The purpose in this would be to allow people to more easily pre-package scripts in datapacks (and thus able to be present in the data folder of extension mods)

Of course, this is purely an enhancement and mcfunction files provide a primitive method of doing this already.

**Comment by altrisi** [comment]
This issue would be better suited to the Carpet repo, [gnembon/fabric-carpet](https://github.com/gnembon/fabric-carpet), since this one is now for issues related to apps in here/app suggestions (and because other feature requests and Scarpet bugs have been transferred in the past there).

**Comment by altrisi** [comment]
Let me close this, since this should be in gnembon/fabric-carpet instead and there is actually already an issue in there.

Feel free to add your ideas in the Carpet issue and to open any other issue that arises.
