### ISSUE TITLE
WE conflicts with /cs carpet script 

### ISSUE THREAD

**Issue by Syntro42** [gnembon/scarpet#199]
The /cs command from Worldedit does not allow a /cs carpet script command to function.

I expect it to run the /cs command from a carpet script instead of the /cs from worldedit

How to reproduce:
1. Go into a singleplayer world while having WE 7.2.4 and Fabric-Carpet 1.4.29 in your mods list as well as a carpet script that uses the /cs command to function (such as: https://github.com/gnembon/fabric-carpet/wiki/Cam-app; rename the script to cs) in your world save folder
2. Type '/script load cs'. Log out. Type '/cs' and observe that the script does not stay loaded (even with /carpet scriptsAutoload true)

**Comment by Firigion** [comment]
Dat user support.

tl;dr: change the app's name.
