### ISSUE TITLE
[Question] How to use /locate_block

### ISSUE THREAD

**Issue by DillonB07** [gnembon/scarpet#206]
How do I use the `/locate_block` script?
I have it on my server loaded but I don't understand the required arguments for the command.

**Comment by altrisi** [comment]
From a quick look at it, it seems to be something like:

`/locate_block locate [radius] [centerX] [centerY] [centerZ] [block]`

`/locate_block hist [radius] [centerX] [centerY] [centerZ] [block]`

It says that `locate` prints a list of up to the first 100 found matching blocks with position and a button to teleport, and `hist` makes a chart of its distribution over y values.

**Comment by DillonB07** [comment]
Thanks!
Sorry I responded really late but this is very useful.
