### ISSUE TITLE
[Question] Difference between vacuum.sc and shulkerboxes.sc

### ISSUE THREAD

**Issue by DillonB07** [gnembon/scarpet#208]
^^^^^
What is the difference between these two scripts?
[https://github.com/gnembon/scarpet/blob/master/programs/survival/vacuum.sc](https://github.com/gnembon/scarpet/blob/master/programs/survival/vacuum.sc)
[https://github.com/gnembon/scarpet/blob/master/programs/survival/shulkerboxes.sc](https://github.com/gnembon/scarpet/blob/master/programs/survival/shulkerboxes.sc)

**Comment by Hibiii** [comment]
I'm not qualified to answer but I took a quick look and it seems that vacuum.sc is just rename a shulker to anything and the word `vacuum` and it'll do vacuuming, while shulkerboxes.sc implements vacuum and `restock` with the same.

**Comment by DillonB07** [comment]
I see. Thanks.
