### ISSUE TITLE
Windows Installer can't find "path specified" preventing download.

### ISSUE THREAD

**Issue by ScarpetUser** [gnembon/scarpet#21]
The installer does not allow me to specify where mine craft is located on my computer.

>>

The system cannot find the path specified.
to patch client, you need to run 1.13.2 game at least once
Press any key to continue . . .

<<

Pressing any key closes the console. I've already ran, and re-ran the 1.13.2 patch. 

Also, 7za.exe does nothing besides instantly crashing for me, even if ran as a admin.

**Comment by Conando025** [comment]
Check that in you're MC folder is an versions folder

**Comment by ScarpetUser** [comment]
There is a versions folder.

**Comment by gnembon** [comment]
What is the full path where your Minecraft is located. Also does it contain '1.13.2' folder with '1.13.2.jar' in it, or it is using some different naming convention?

**Comment by ScarpetUser** [comment]
C:\Users\*my name*\AppData\Roaming\.minecraft\version\1.3.2
I looked at the code for the executable and it didn't have the Roaming part. I changed the minecraft file location to be in AppData instead of Roaming and it still doesn't work (And reverted it as well). running the "Run" program doing %appdata%\.minecraft\version\1.3.2 brings up the the correct file, so I'm super confused.

**Comment by gnembon** [comment]
isn't the version we are talking about 1.**13**.2, not 1.3.2?

**Comment by ScarpetUser** [comment]
Yes, Sorry. That's a spelling mistake.

**Comment by gnembon** [comment]
If your username had space in the name, then that was an issue with the installer. Try now with 'sunny' or later release and let me know, otherwise closing.

**Comment by PegasusEpsilon** [comment]
Given the lack of reply since June, you can probably close this one, @gnembon...
