### ISSUE TITLE
(1/2)/3 returns 6

### ISSUE THREAD

**Issue by JackRedstonia** [gnembon/scarpet#210]
**Describe the bug**
Evaluation of `(1/2)/3` or `1/2/3` in the `/script run` command returns `6`.

**To Reproduce**
1. Ensure `commandScript` is on: `/carpet commandScript ops` or `/carpet commandScript true`
2. Run `/script run 1/2/3` or `/script run (1/2)/3`
3. Receive `6` as the result.

**Expected behavior**
The command returns a value around `0.166666666667`.

**Screenshots**
No screenshots, but here is the relevant server log.
```
script run (1/2)/3 
[16:03:09] [Server thread/INFO]: Input code size for system chat: 5 nodes, 3 deep
[16:03:09] [Server thread/INFO]: Compacted from 5 nodes, 3 code depth to 4 nodes, 2 code depth
[16:03:09] [Server thread/INFO]: Optimized from 4 nodes, 2 code depth to 1 nodes, 1 code depth
[16:03:09] [Server thread/INFO]:  = 6 (523µs)
script run 0.5/3
[16:03:14] [Server thread/INFO]: Input code size for system chat: 3 nodes, 2 deep
[16:03:14] [Server thread/INFO]: Optimized from 3 nodes, 2 code depth to 1 nodes, 1 code depth
[16:03:14] [Server thread/INFO]:  = 0.166666666667 (476µs)
```

**Environment**
 - Carpet version: 1.16.5-1.4.37+v210519
 - Minecraft version: Fabric server 1.16.5

**Additional context**
None, for now.

**Comment by altrisi** [comment]
Wait, actually I never realized you reported this in the scarpet repo until now (now it makes sense why I got pinged).

Bugs and feature requests in the Scarpet language should be reported in the Carpet repo ([gnembon/fabric-carpet](https://github.com/gnembon/fabric-carpet/)). Could you reopen it there instead? That way it's easier for @gnembon to catch it (pinging you in case you want to transfer it directly).

This repo is for bugs in scarpet apps in the repo, app suggestions, and scarpet questions (though the last ones are usually resolved faster in the discord).

**Comment by altrisi** [comment]
Recreated it in gnembon/fabric-carpet#874.

**Comment by gnembon** [comment]
🤦  ma bad

**Comment by JackRedstonia** [comment]
it ok
hope this pic make you feel better

![dce89d1](https://user-images.githubusercontent.com/74783030/119268859-08a57000-bc1f-11eb-963a-02d502d0ed5c.png)
