### ISSUE TITLE
Water blocks are rendered after scarpet draw_shape rendering

### ISSUE THREAD

**Issue by Crec0** [gnembon/scarpet#214]
**Describe the bug**
Water is rendered above the scarpet draw_shape which causes it to look weird and unnatural.

**To Reproduce**
1. draw any shape using draw_shape function from scarpet above a water body or water block

**Expected behavior**
Water should be under the drawn shape when shape is drawn above the water

**Screenshots**
![image](https://user-images.githubusercontent.com/83436716/120285122-d07edc80-c271-11eb-8b0c-cc281d108bac.png)

**Environment**
 - Carpet version: 1.4.38+v210527
 - Minecraft version: 1.16.5

**Comment by Crec0** [comment]
Sorry for the bright pink. :P

**Comment by altrisi** [comment]
Note that this repo's issues is for issues and suggestions in scarpet apps hosted in here (and scarpet support). Issues about errors and feature requests in the scarpet language should be reported to the main [gnembon/fabric-carpet](https://github.com/gnembon/fabric-carpet/) repo (here it would still be noticed, but usually much later, and all in all would be moved there).

**Comment by Crec0** [comment]
@altrisi Ah okay. I will report them there
