### ISSUE TITLE
Add libraries folder in programs folder

### ISSUE THREAD

**Issue by rv3r** [gnembon/scarpet#227]
When authors write functions to perform actions that many other authors might need, they could submit a library of functions to this folder. This would allow other authors to use past work instead of rewriting a new function, and it would be easier to find a library you're looking for since it must be in this folder.

**Comment by altrisi** [comment]
Git can't have empty folders, so when someone adds one, I'll approve.

**Comment by Ghoulboy78** [comment]
Maybe could rename `fundamentals` folder? cos rn it contains useful maths stuffs, but could easily be repurposed to be a general libraries folder. @gnembon waddya think?

**Comment by rv3r** [comment]
This was done at some point.
