### ISSUE TITLE
view functions

### ISSUE THREAD

**Issue by Conando025** [gnembon/scarpet#23]
I've made a function a few days ago and run it. Now I wan't to chane some bits and pices, but I havn't save a file and the commandblock is destroyed. Is there a way to look up, how my Function worked?

**Comment by gnembon** [comment]
It seems like you have removed the file with it, which is like deleting a document. I don't think I could help you with it, sorry.

**Comment by Conando025** [comment]
So to later look up what my functions was, I have to save it in a file right?

**Comment by gnembon** [comment]
yeah - editing functions in commandblocks is rather painful. 
I will be adding support to loading programs from disk, similarily what you have with datapacks.
