### ISSUE TITLE
How to modify auto_light script to light surface as well?

### ISSUE THREAD

**Issue by lasofeli** [gnembon/scarpet#233]
I feel like I'm missing something basic. Taking a look at gnembon's auto_light script, it feels like it should be easy to modify it to also light up the surface and not just caves.

My attempt was to simply delete the 'skylight' requirement for one of the if statements in the spread_torches function. Upon reloading and running it in-game however, I find that the script still doesn't send torches to the surface.

So, yeah. I'm kinda stumped here. Best I could imagine is that it maybe distinguishes caves using the cave_air/regular air thing, but I can't find where in the code it distinguishes between the two (if that is how it works)

**Comment by Firigion** [comment]
it should be as easy as removing `&& sky_light(lpos)<8` from [this line](https://github.com/gnembon/scarpet/blob/29f2adf1940a3b3c0a8efea40d29aff30d1f56c4/programs/survival/auto_lighter.sc#L50)

**Comment by lasofeli** [comment]
Huh. Well it works now, but I swear when I tried this earlier, it didn't work at all. Oh, well.
