### ISSUE TITLE
An unexpected error occurred trying to execute that command

### ISSUE THREAD

**Issue by Conando025** [gnembon/scarpet#24]
After running `/script invoke _haus` it spills that error message out. Any Ideas why it does that?
`script run _haus() -> (
$  set(-11,102,37, 'structure_block'); run('data merge block -11 102 37 {mode:"SAVE", posX:1, posY:0, posZ:1, sizeX:13, sizeY:11, sizeZ:11, showair:0, ignoreEntities:0, name:"haus:1"}');
$  set(-12,102,36, 'structure_block'); run('data merge block -12 102 36 {mode:"SAVE", posX:1, posY:0, posZ:1, sizeX:2, sizeY:2, sizeZ:2, showair:0, ignoreEntities:0, name:"haus:1"}');
$  set(-10,103,38, 'structure_block'); run('data merge block -10 103 38 {mode:"LOAD", posX:-1, posY:-1, posZ:-1, name:"haus:1"}');
$  set(-10,102,38, 'structure_block'); run('data merge block -10 102 38 {mode:"LOAD", posX:0, posY:0, posZ:0, name:"haus:1"}')
$)`

**Comment by cheese3660** [comment]
I'm having the same problem but with killing entities,
`/script run 
duster() ->(
$   dusted = 0;
$   print('*Snap*');
$   for (entity_list('*'),
$       ent = _;
$       if (bool(rand(2))==1,
$           (
$                   print('/kill @e[x='+query(ent,'x')+',y='+query(ent,'y')+ ',z='+query(ent,'z')+',dx=0.5,dy=0.5,dz=0.5]');
$                   (
$                       
$                       run('kill @e[x='+query(ent,'x')+',y='+query(ent,'y')+ ',z='+query(ent,'z')+',dx=0.5,dy=0.5,dz=0.5]');
$                       dusted=dusted+1
$                   )
$           )
$       )
$   );
$   dusted
$);`

**Comment by gnembon** [comment]
Snap - its a bug. 'run' was implemented when x, y, and z were globally available variables. Now as each function has its own variables, and x, y, z which is where script is executed (for commands ~) is not available  (hence NPE). 
Will fix it properly for the next release, but a dirty fix is wherever in a function you use 'run', just put 
l(x,y,z) = l(0,0,0); - that fixes it.

Thanks for spotting that out.

**Comment by gnembon** [comment]
btw @cheese3660 
I don't know what are you trying to achieve, but you might get much better performance with using 
for(entity_area('*', ent ~ 'x', ent ~ 'y', ent ~'z', 0.5, 0.5, 0.5), modify(_, 'remove'))

modify(e,'remove') is much more imminent and cleaner, than 'kill' unless you want to simulate in game death.

**Comment by gnembon** [comment]
Just push a fix to master in github.com/gnembon/carpetmod
If you are comfortable to built from the dev repo - should be working as of now - otherwise it will come out in the next update:
https://github.com/gnembon/carpetmod#tldr-to-help-us-develop-carpet-mod
