### ISSUE TITLE
sleep_ignore_fake_players.sc make that a thunderstorm appends next day

### ISSUE THREAD

**Issue by Th3D0c** [gnembon/scarpet#241]
When loaded every time you sleep a thunderstorm will append next day. Sleeping to end the storm result in another storm next day and so on.

1. Load the script in a game
2. Wait and sleep when you can
3. Wait for around mid day and a thunderstorm should start

**Expected behavior**
When sleeping with fake players around there should be a normal chance of having bad weather.

**Environment**
 - Carpet version: Carpet Jar Mod v19_06_04 with Scarpet v1.3 on Fabric 0.7.4
 - Minecraft version: Minecraft 1.17.1
 - Other mods: malib, litematica, item scroller, tweakaroo, modmenu

**Comment by JumperCzech** [comment]
still an issue on 1.18.1
