### ISSUE TITLE
When using a colon to index an nbtcompound, if an array or list is returned, the result will be of type string rather than type nbt.

### ISSUE THREAD

**Issue by ch-yx** [gnembon/scarpet#242]
When using a colon to index an nbtcompound, if an array or list is returned, the result will be of type string rather than type nbt.

although a list could be of type nbt
```
/script run a=nbt('[1]');type(a)                    #nbt
/script run a=nbt('{a:[1]}');type(a:'a')            #string
```
bytheway 
```
/script run a=(nbt('{a:[1]}'):'a')                      #crash
```

**Comment by altrisi** [comment]
Closing this in favour of gnembon/fabric-carpet#1080, since there's where language/API bugs go.
