### ISSUE TITLE
keepalive.sc doesn't spawn players after /stop

### ISSUE THREAD

**Issue by anaxios** [gnembon/scarpet#247]
keepalive script doesn't respawn players after restart. 

I tried setting the commandPlayer option to true instead of ops and I tried it without the Rules mod.

running:
  fabric-server-1.17.1-0116
  fabric-carpet-1.4.46

**Comment by Firigion** [comment]
Maybe `__on_server_shuts_down` doesn't trigger with `/stop`? If that's the case, how about saving the palyer data each time a player is spawned. It's not like that's gonna happen that often anyway.

**Comment by Ghoulboy78** [comment]
Ye, this may be a carpet bug... I will investigate.

**Comment by Ghoulboy78** [comment]
Well it appears to work, except we don't preserve the fake players' flying state (i.e., flying players don't remain flying). I've fixed that now and will submit a pr for it.
