### ISSUE TITLE
Cam app sends a blank line in chat

### ISSUE THREAD

**Issue by ZachTheDev** [gnembon/scarpet#250]
**Describe the bug**
When using /cam, a blank line is put in chat
or for other users it displays their username like so [username: ]
**To Reproduce**
1. install cam
2. use /cam
3. see blank line

**Expected behavior**
No blank line

**Comment by Ghoulboy78** [comment]
Ye I noticed that too, lemme see if I can find where it happens

**Comment by Ghoulboy78** [comment]
https://github.com/gnembon/scarpet/blob/071311fded1f7e3b9fdcdeaa5509babe413060da/programs/survival/cam.sc#L65-L67
Thats the bug, cos it returns that and therefore prints that.
To fix it, line 66 should be replaced with a newline.

**Comment by ZachTheDev** [comment]
@Ghoulboy78 Thanks! I totally passed over that line since I do not really understand scarpet syntax. Thanks!
