### ISSUE TITLE
Rename `shapes.sc`

### ISSUE THREAD

**Issue by altrisi** [gnembon/scarpet#258]
It shadows the built-in `shapes.scl`, leading to all sorts of problems with apps depending on that (since the ones from `shapes.sc` will have preference when being imported). It already made me loose almost half an hour.

**Comment by altrisi** [comment]
Any idea what to call it btw?

**Comment by Ghoulboy78** [comment]
Ye, thats bad. Tbh it could also do with a rewrite, and some of the stuff already exists in `distance_beta.sc` rn, and I could add the thickness option to `shapes.scl` as well as `draw_beta.sc` if gnembon approves, cos tbh it looks cool.

As for renaming, we could use `forms`, or maybe `drawing_tool`? ok maybe none of them cos these a bad suggestions, but my point is some variation on a synonym of the word `shapes`.

**Comment by Firigion** [comment]
Oh damn. `shapes.sc` was first, that's why nobody noticed until now. I'd just rename it into `sshapes` for scarpet shapes and call it a day. Tell me if you want me to do the PR.
