### ISSUE TITLE
`auto_lighter` still uses the old mob spawning light level

### ISSUE THREAD

**Issue by altrisi** [gnembon/scarpet#277]
In 1.18, the minimum light level to prevent mobs from spawning was set to 1. However, `auto_lighter` still uses 8, making it spam considerably more torches (and therefore wasting them if in survival mode).

Proposed changes:
- Updating it to the new 1.18 default
- Make the minimum light level exist in a global so it can be changed easily at the top
- Document that global in the wiki page about the app

Additions that could go with it, but aren't directly related to this issue:
- A global to disable sky light check
- Making it not care about sky light by default

**Comment by Firigion** [comment]
Why not use `system_info('game_major_target')` to decide on launch?

**Comment by Ghoulboy78** [comment]
Fixed in #296
