### ISSUE TITLE
Running command as a stored entity

### ISSUE THREAD

**Issue by Minepig** [gnembon/scarpet#31]
I found that the run() function only has 1 parameter which is the command itself, and the command seems to be run as console at the world origin. I have to use the 'execute' command with the vanilla entity selector to specify the runner and the position. I hope that the run() function can have some parameter such as 'runner' and 'pos' so that I can run a command as an entity which has been stored into a variable, or at a position which has been stored into a list.

**Comment by gnembon** [comment]
I thought about not providing this since the game already has mechanics to allow to customize the command source via /execute command and thought that's how it would be used.
Does it still pose some limitations that I don't see in this case, or this is a sufficient solution?

**Comment by Minepig** [comment]
Recently I have found the solution using " entity ~ 'uuid' ". Maybe I just neglected that before.
