### ISSUE TITLE
[Question] Veinminer - player ~ 'sneaking'

### ISSUE THREAD

**Issue by qwewer0** [gnembon/scarpet#324]
In the veinminer.sc, is there a way to change the default `player ~ 'sneaking'` to a button is held?
e.g. if the player is holding down the `x` button.

**Comment by Crec0** [comment]
Scarpet cannot do keybinds. So nope

**Comment by Ghoulboy78** [comment]
As mentioned, that is not possible because keybinds are client side, not server side. You could do it by rebinding the sneak key to whatever key you want for veinmining, but at that point you might as well just use the sneak key tbh.
