### ISSUE TITLE
Rift does not support 1.19 or 1.18 

### ISSUE THREAD

**Issue by Danjhop4** [gnembon/scarpet#330]
Does what the title says only bugs are allowed here

**Comment by Ghoulboy78** [comment]
This is a known issue, cos of the way dimension handling has been changed in recent versions.
I'm afraid as of rn, there is no way to fix it, but in the future it may not be the case, who knows.

**Comment by Danjhop4** [comment]
Tried to replace the worldgen files idk if it works
