### ISSUE TITLE
world_map.sc not loading even after placing it in scripts folder

### ISSUE THREAD

**Issue by Brokoth** [gnembon/scarpet#340]
I downloaded the world_map.sc app and placed it into my global scripts folder as stated in the docs
![image](https://user-images.githubusercontent.com/42600065/191802409-0dec6f33-99fc-4f76-82ab-0ce55159643c.png)
 yet i am unable to load the app in game
![image](https://user-images.githubusercontent.com/42600065/191803119-104e75ec-0667-4a86-9b08-f230e4b69385.png)
I have also tried adding the app to my worlds scripts folder but still encountered the same error.
I note that the scripts in the below image work ok (i guess this are default apps? I cant see them in any of my script folders though)
![image](https://user-images.githubusercontent.com/42600065/191803469-67def09b-b92e-4e35-97ae-6474dab35016.png)
Any assistance would be greatly appreciated.
For the record i am running 1.19.2 and carpet mod version 1.4.83

**Comment by SurfingDude-1182** [comment]
Not a 100% sure but check the carpet folder inside config. If I remember correctly, global scripts and global rules go in there.

**Comment by SurfingDude-1182** [comment]
Also world map seems to be broken in newer versions. #280 Fix hasn't been approved yet it seems.

**Comment by altrisi** [comment]
An easier way to download apps from this repo specifically btw is running `/script download <path>`, which should put it in the correct place and load it too.

**Comment by Brokoth** [comment]
@altrisi i tried this diretory too `.minecraft/config/carpet/scripts>` but it still didn't work. I would like to try this `/script download <path>` command. what value should i put under the `<path>` variable?

**Comment by altrisi** [comment]
The path from the [programs folder](https://github.com/gnembon/scarpet/tree/master/programs) to the script, so in this case `survival/world_map`.

Note though that the world map app doesn't currently work in 1.19, given there's been a lot of generation changes since it was made.

**Comment by Brokoth** [comment]
This worked. I note that when downloading directly from the repo an additional file was generated. Maybe this missing file was the reason the script wasn't working?
![image](https://user-images.githubusercontent.com/42600065/191825063-99726c02-2ffa-44af-a43e-ef49c49125fe.png)
In any case thanks @altrisi for the guidance. Much appreciated.

**Comment by altrisi** [comment]
No, that's produced by the app when running to save its data.
