### ISSUE TITLE
Camera app won't install

### ISSUE THREAD

**Issue by unofficialreece** [gnembon/scarpet#341]
**Describe the bug**
The camera module app won't install because there is an error (Error while evaluating expression). More information about the errors below.

**To Reproduce**
1. Type the command `/script download utilities/camera.sc`
2. An error occurred.

**Expected behavior**
The Camera app is supposed to be installed properly with no errors.

**Screenshots**
![2022-09-23_02 26 03](https://user-images.githubusercontent.com/79681820/191834446-dff29dcd-f42d-4581-b8c7-b309cb00aba7.png)

**Environment**
 - Carpet version: 1.4.83
 - Carpet Extra version (if needed): 1.4.83
 - Minecraft version: 1.19.2
 - Quilt version: 0.17.5-beta.2

**Comment by altrisi** [comment]
That camera app is now built into Carpet, you can load it with just `/script load camera` (after removing the broken copy from your scripts folder).

Note that `camera` is the app to make camera paths and stuff, if you want the one for going into spectator mode it's in `survival/cam.sc`.
