### ISSUE TITLE
Sub-Folder scripts support

### ISSUE THREAD

**Issue by IceWolf23X** [gnembon/scarpet#347]
**Is your feature request related to a problem? Please describe.**
A more orderly script management

**Describe the solution you'd like**
Add support for subdirectories such as `/scripts/MyFolder/myscript.sc`, `/scripts/MyFolder/myotherscript.sc`

In this case, to load it into the game just use the command `/script load MyFolder/myscript` or `/scripts/MyFolder/myotherscript.sc`, etc

In the case of files defined as `"shared_ #"` they will be generated inside the `MyFolder` folder, and in the case of files not `"shared_ #"` a subfolder will be created eg: `/MyFolder/myscript.data/[file here]`

**Describe alternatives you've considered**
Currently, none

**Additional context**
Very convenient in the event that a player wants to use a large variety of scripts from various developers who may find themselves having similar if not identical names, making it difficult for an average player who cannot handle the code of the scripts to use.

**Comment by Ghoulboy78** [comment]
This is a request for [gnembon/fabric-carpet](https://github.com/gnembon/fabric-carpet/issues), cos that's for requests about scarpet implementation.
