### ISSUE TITLE
replace_inventory not working correctly

### ISSUE THREAD

**Issue by Guty18** [gnembon/scarpet#348]
**Describe the bug**
It's inconsistent, it will work for a while and then stop working. I'm using linemtica printer in survival and when the stack runs out it doesn't re-fill it, is there any way to make the refill function work with 10 items left in the slot or so? I tried looking into the code but I can't see a variable like "item refill threshold" to modify.

Thanks

**Environment**
 - Carpet version: 1.4.84
 - Minecraft version: 1.19.2

**Comment by rv3r** [comment]
> is there any way to make the refill function work with 10 items left in the slot or so?
Yes, but the script would have to move less than a full stack, making it much more complex. That can be done, but I'd probably want to rewrite all the inventory management apps to have a refill threshold like Tweakeroo.

Is there any more information you can provide on when the script stopped working? What you were placing, what was in the box, what your inventory looked like, were you using Tweakeroo fast block placement, etc.

**Comment by Guty18** [comment]
I've been using the other script for inventory refill and it works fine, thanks for the help.

P.S. It's been so long that I don't remember what the issue was exactly.

**Comment by rv3r** [comment]
Interesting. Well, at least you have something that works. Guess I'll close this issue.
