### ISSUE TITLE
Missing apps in the readme

### ISSUE THREAD

**Issue by altrisi** [gnembon/scarpet#360]
I made a quick java script to check for missing entries in the `survival` folder, and it found the following ones:
- [x] `bridge_maker.sc`
- [x] `combine_xp_orbs.sc`
- [x] `easier_renewable_sponge.sc`
- [x] `flippin_cactus.sc`
- [x] `item_holding_mobs_despawn.sc`
- [x] `no_useless_llamas.sc` (different format)
- [x] `showbiome.sc`
- [x] `show_bees_count.sc`

~~I haven't yet checked if some may be just that the title is not formatted the same way.~~

**Comment by altrisi** [comment]
`no_useless_llamas` seems to be using a different format than the rest, `rifts` is a folder (didn't check if it was file or folder), the rest are correct.

**Comment by Ghoulboy78** [comment]
I updated it so it's a list, so I can just tick them off as I add them one by one.
