### ISSUE TITLE
Having issues getting shulkerboxes.sc to work on a server

### ISSUE THREAD

**Issue by tr4k41s** [gnembon/scarpet#374]
No matter which way i name the boxes none of the functions work, running carpet version 1.4.101 - 1.19.4
What i've tried:
Reloading the script, reinstalling the script, removing all mods except carpet and fabric api from the server, making a new server with the same world file
The script works fine when i use the same world folder in a singleplayer world

**Comment by rv3r** [comment]
Can you share exactly how you named the boxes and what you tried to do with them?

**Comment by rv3r** [comment]
Alright crazy idea but you did load the script right? Doesn't hurt to check. Sorry for the simple requests but, I'm having trouble reproducing this, so I'm probably gonna ask everything.

**Comment by tr4k41s** [comment]
Well I tried downloading the script manually and then using /script load shulkerboxes, tried /reload multiple times on this aswell, also tried downloading the script using /script download survival/shulkerboxes.sc and then repeating what i did whilst downloading it manually.

**Comment by rv3r** [comment]
Thanks for the update. I honestly had no clue on this one so I'm glad to hear it was the other mod.
