### ISSUE TITLE
cam.sc does not load pre-/cam location.

### ISSUE THREAD

**Issue by Notoriousi** [gnembon/scarpet#377]
**Describe the bug**
When entering /cam all seems normal, however when you leave /cam it just changes your gamemode. see video: https://youtu.be/a6AkfL-PmV0

Video was taken with a fresh install of the /cam script.

Carpet settings: 
![image](https://github.com/gnembon/scarpet/assets/94121814/0edd7b86-f660-4be4-9ab0-8a82413a8d02)

Mods running on the server: 
![image](https://github.com/gnembon/scarpet/assets/94121814/f5a2fc34-cddd-462b-a27f-3a756e21b9e6)

**Comment by petersv5** [comment]
Same issue here with fewer mods installed as well. The issue seems not to be present in 1.20.2 and definitly present in 1.20.4.

**Comment by petersv5** [comment]
This is strange. A command like 
  /script run modify(player(), 'pos', [100, 100, 100])
takes effect as expected. However, when I add
  print('at end of restore_player);
  modify(player(), 'pos', [100, 100, 100]);
at the end of __restore_player_params() I get the printout but the player does not move. I am at a loss why they work differently. Is this a bug in the carpet script engine itself?

**Comment by petersv5** [comment]
It is the "run('execute in minecraft:'+config:'dimension'+' run tp @s ~ ~ ~');" command that inhibits / overwrites subsequent pos updates.

**Comment by petersv5** [comment]
As a workaround I removed 'pos' from the for loop in __restore_player_params() and modified the teleport line to read:
   [x, y, z] = config:'pos';
   run('execute in minecraft:'+config:'dimension'+' run tp @s '+x+' '+y+' '+z);

This made the script work again.

**Comment by Notoriousi** [comment]
> As a workaround I removed 'pos' from the for loop in __restore_player_params() and modified the teleport line to read: [x, y, z] = config:'pos'; run('execute in minecraft:'+config:'dimension'+' run tp @s '+x+' '+y+' '+z);
> 
> This made the script work again.

Could you maybe make a pull request? Idk what to edit myself but I'd love to try your method
