### ISSUE TITLE
storage drawers example currently doesn't work for modded items

### ISSUE THREAD

**Issue by Nathan22211** [gnembon/scarpet#40]
this might be because you seem to only retrieve the item's name after the modID. which in my experience you need to retrieve the entire string for it to work with modded items.

**Comment by gnembon** [comment]
I would probably need to make sure the path is stripped only from vanilla names, not modded. I would like to maintain simplicity and compatibility with vanilla commands where you can just type `setblock x y z stone` and it works. I will revise item API to make sure mod prefixes are retrieved for non-vanilla items. It would be up to the programmer to take care of that.

**Comment by gnembon** [comment]
I fixed how scarpet returns names of items, blocks, entities, etc. and for modded identifiers, it will include the modid prefix. After that's released I will update the scripts to take care of that.

**Comment by gnembon** [comment]
checked - works
