### ISSUE TITLE
Issue with Gnembon Autolighter

### ISSUE THREAD

**Issue by jwattsy** [gnembon/scarpet#42]
![1](https://user-images.githubusercontent.com/57697458/68926116-ba263400-0752-11ea-8ed8-e8c475ac0c96.PNG)
New to coding and keep getting this error, I don't know what to replace it with. When I take out "a", a new error comes up saying "torch" can't be placed after "can"

**Comment by PMX-Universe** [comment]
If you run the code directly in a commandblock you must remove all comments starting with //

**Comment by gnembon** [comment]
yeah, in commandblocks there is no notion of 'newline' so comments are not allowed. Put the file in the world /scripts folder (might need to create it), and use /script load autolighter
