### ISSUE TITLE
Holy Hand Grenade 1.15 server

### ISSUE THREAD

**Issue by jusTinMan** [gnembon/scarpet#46]
Holy Hand Grenade on a 1.15 fabric server will crash it, but on a single player world using the fabric client it works fine. I am sure it is a bug with the fabric server version. I think the vine-miner doesn't work ether.

**Comment by jusTinMan** [comment]
[crash-2019-12-16_23.31.20-server.txt](https://github.com/gnembon/scarpet/files/3970643/crash-2019-12-16_23.31.20-server.txt)

Crash report attached

**Comment by Yggdraszil** [comment]
The same thing happens with the auto lighter script on 1.14.4 so [this](https://github.com/gnembon/scarpet/issues/45) issue is unfortunately not fixed.

**Comment by jusTinMan** [comment]
still broken in 1.15.1

**Comment by gnembon** [comment]
thanks for noticing. Will be fixed in carpet 1.3.2

**Comment by jusTinMan** [comment]
Looks like it is working! Thanks!
