### ISSUE TITLE
function"tick()" is not defined

### ISSUE THREAD

**Issue by Harveykang** [gnembon/scarpet#47]
![image](https://user-images.githubusercontent.com/46108547/71553946-ecfe6000-2a52-11ea-88bb-8bdc12ff54b5.png)
![image](https://user-images.githubusercontent.com/46108547/71553959-1cad6800-2a53-11ea-928c-152dfe64e8a5.png)
i can't find any other discription about "tick()" but this(in picture), maybe i misunderstanded something?

**Comment by gnembon** [comment]
sorry, error in documentation. should be game_tick()
