### ISSUE TITLE
[suggestion]make scarpet read .sc files default use UTF-8 encoded instead of system default, now it use ANSI on my computer, use UTF-8 on my server

### ISSUE THREAD

**Issue by Harveykang** [gnembon/scarpet#52]

**Comment by gnembon** [comment]
What if someone edits a program locally with 'system defaults' and have problems loading app in the game - why forcing UTF-8 is beneficial in this case?

**Comment by Harveykang** [comment]
ummm, could scarpet specify the code set in the document header? that's also fine

**Comment by altrisi** [comment]
Related if not fixed by gnembon/fabric-carpet@ea52048f3db9f1e93b0abe6c6d95d8f73d10e61f.
