### ISSUE TITLE
Function values dont persist

### ISSUE THREAD

**Issue by Flutterish** [gnembon/scarpet#54]
In this code:
```
Object = m( l( 'myFunction', fun (x) -> ( print(x) ) ) );
call( Object : 'myFunction', 'Hello World!' );
```
I get an error "function 0 is not defined yet at position...".
Further testing revealed that all functions return a numerical value that cannot be called.
For example:
```
myCall( fun, param ) -> ( call( fun, param ); );
myCall( print, 'Hello World!' );
```
Gives me the same error.
Changing the scope to global does not fix this issue either.

**Comment by Flutterish** [comment]
Creating a method with `_(...)->(...)` does work however.
This does provide a workaround, but it is inconvinient.

**Comment by gnembon** [comment]
this is weird

**Comment by gnembon** [comment]
I mean your report is valid. named functions should not behave differently, apart from being named, comparing to lambdas (unnamed functions).

**Comment by gnembon** [comment]
also in 
```
fun ( a, b ) -> ( print( a * b ); );
obj = m( l( 'mult', fun ) );
```
second `fun` refers to the new variable that hasn't been initialized, `fun` is a variable, `fun()` is a function, `'fun'` is that function name, that you can call in with `call()`, or you should be able to grab function reference as well with `fun = ( fun() -> foo() );  call(fun);`  (not sure if you need the outer brackets around the function definition, probably)

**Comment by Flutterish** [comment]
I can see why assigining the functons reference to a variable with the same name implicitly would cause trouble, but I'm sure there is a way to prevent it? Like, do it only for this and lower scopes? That is
```
main(...) -> (...); // implicit "main = ( _(...) -> main(...) )" in this scope
print( main ); // function main
x = m( l( 'foo', main(...) -> (...) ) ); // implicit --||-- but for only for l(...) scope
print( main ); // same function
print( x : 'foo' ); // the other function main
```

**Comment by gnembon** [comment]
going back to your first example:
```
Object = m( l( 'myFunction', fun (x) -> ( print(x) ) ) );
call( Object : 'myFunction', 'Hello World!' );
```
works, getting print output and same text as a result of a function, which is expected (print passes through its argument)

second example is also correctly incorrect
`print` is an identifier, and as undefined assumes value of `0`
call(0,..) checks if first argument is a function, else takes a string value of expression, and calls it a function to call, in this case `0`

what would work is:
```
myCall( fun, param ) -> ( call( fun, param ); );
myCall( _(x) -> print(x), 'Hello World!' );
```
one problem allowing previous syntax, apart from overloading variable space with duplicates of built in functions, is that built-in functions can take any arbitrary number of arguments and one thing with `call` is verifies arguments. Not really important with `call`, but could be ambiguous with `task(...`, which is essentially `call_async` or `apply_async`
