### ISSUE TITLE
Add special characters to string values

### ISSUE THREAD

**Issue by Flutterish** [gnembon/scarpet#55]
Currently `'\r\n\t'` etc. print as `'rnt'`.
If one would want to include them, they would need to write
```
'
    '
```
instead.

**Comment by gnembon** [comment]
hmm, minecraft strips all special characters from strings anyways. I would try to explore how to convince them to do otherwise.

**Comment by Flutterish** [comment]
It strips them from \script files?
Because when I run `print( '\r\n\t' );` from an .sc file, it prints 'rnt'. But when I run
```
print( '
    ' );
```
it prints correctly.
I can see how it would remove actual special characters from a chat/command block command but I think the problem is that scarpet doesnt interpret escaped characters correctly.

**Comment by gnembon** [comment]
I tried to pass \n and \t to minecraft text objects but it strips them out. What you are saying is replacing those with actual newlines, tabs might actually work, so \t and \n will be translated into proper things in the output. I will give it a shot.

**Comment by gnembon** [comment]
so,
new lines work, but other special characters turn into some random placeholder crap. Will allow \n for newlines, but \t and \r will raise exceptions not to use them.

**Comment by Flutterish** [comment]
Interesting that `\t` doesnt work. In VS Code, an actual tab in a string is correctly printed in minecraft. Im not sure how you implemented the tab, but maybe it has something to do with either the file format or how your code editor saves tabs?

**Comment by gnembon** [comment]
![2020-01-10_21 22 20](https://user-images.githubusercontent.com/41132274/72196555-6ef56e00-33ef-11ea-9989-757f3922ae6a.png)
![Capture](https://user-images.githubusercontent.com/41132274/72196581-9d734900-33ef-11ea-83bf-29f6b2246325.PNG)
I don't understand what do you mean by prints properly. Do you get something like I get or proper white spaces?

**Comment by Flutterish** [comment]
I get proper white spaces.
![image](https://user-images.githubusercontent.com/40297338/72212290-958fd380-34d9-11ea-94a0-3e4dce18cf68.png)
and my code which is a mess due to the fact that i didnt have escaped characters
![image](https://user-images.githubusercontent.com/40297338/72212301-b8ba8300-34d9-11ea-975a-0a46ed3e2cbe.png)
Have you checked if `\t` prints correctly if and only if its the FIRST character of a line?

**Comment by gnembon** [comment]
sounds like a vanilla bug to me. I should report it

**Comment by gnembon** [comment]
I added tab character to the list of supported chars mainly due to file read/write support.
