### ISSUE TITLE
[suggestion] You should be able to manipulate scoreboards

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/scarpet#57]
If scarpet is truly going to be used in liaison with normal vanilla datapacks, which would be a nice thing to see, one must be able to manipulate the vanilla variables with scarpet: scores. I envision it as something like this:

    score(scoreboard, entity)
returns score of 'entity' in scoreboard 'scoreboard' .If that entity is not tracked by the scoreboard, returns nothing.
'if(score('health',Ghoulboy)<2,print('Ghoulboy, you are dying!')'

    add('score/entity',name,'score?',value?)
if running with 'score' in first parameter, then rest after 'name' is clearly redundant, scoreboard objective is created and that's it. But if it's 'entity', then you have to add what scoreboard, and 'value' defaults to zero if not specified

    remove('score/entity','name','score?')
No need to guess here

I am assuming that with 'score' command, you will be able to manipulate it like a common variable, so you can set it and add to it as you will, so there will be no need for implementation of vanilla 'scoreboard players add' and 'scoreboard players set' command.
This way you could make datapacks and scarpet scripts interdependent in places where they should be, and make them run one another like:
end of first_function.mcfunction:
    `…
    script run do_important_complex_maths_that_you_cant_do_with_datapacks`

and then to do_important_complex_maths_that_you_cant_do_with_datapacks.sc:
    `…(maths)
    run('function cool_stuff/second_function')`

This way you could make a ton of things like BlingEdit way easier to code as they require tons of function files solely cos they need to do complex calculations what take like three lines in scarpet.

**Comment by gnembon** [comment]
makes sense, althought that would just be the storage place, not the way to do math, like in datapacks

**Comment by Nameless-123** [comment]
Is there no way to make it so you can do math with scores, or read them at the very least? Cos in datapacks maths with scoreboards is dummer than a Republican

**Comment by gnembon** [comment]
you can't. I should add functions to read and write to scoreboards

**Comment by Nameless-123** [comment]
oh ok that would be a nice addition and an easier way to use scarpet apps and datapacks in liaison cos some things are easier with datapacks and some are easier with scarpet apps

**Comment by Nameless-123** [comment]
you could I guess do some thing like this:

`
score_1=get('scores','score1');
(maths with local variable after which...)
put('scores','score1',score_1)
`

**Comment by Ghoulboy78** [comment]
Hey, @gnembon , sorry to ping you but I realized that this is already possible entirely. You just do this:
```
for(entity_selector('@e[nbt="Score{whatever the nbt structure is, idk}"]')
do whatever
);

and to give an entity the score:
nbt=get(entity,nbt)
put(nbt,{Score{again, nbt syntax is unimportant here}})
```
The point is that this is already possible, so should the ticket be deleted? I personally am in favour of keeping it as this is a complex system for something that ought to be very simple, but it's your call

**Comment by Ghoulboy78** [comment]
Please ignore all the above, it is not possible to get it via nbt manipulation

**Comment by Ghoulboy78** [comment]
But wait!
You can still do the first thing using vanilla entity selectors b and you could still technically do 
`run('scoreboard players set '+e+' '+score+' '+value)`
And it wouldnt be too cumbersome, would it? Againb it's your call to simplify things or just leave it as it is, workable,  yet tricky to work out.
Cos Im gonna add a pr to the scarpet docs with a part on Scoreboard manipulation, and then update it if need be

**Comment by Ghoulboy78** [comment]
BREAKING NEWS: After a hair-raising (though for me it was only hair raising cos its hella cold here) summit on the Scicraft discord, gnembon and Ghoulboy (under a neaky pseudonym) may finally have come to an agreement:

`get_score(entity,scoreboard)` which returns the score of the entity in the scoreboard

`put_score(entity,scoreboard,value)` no explanations needed

`create_objective(objectivename,tracking)` creates a scoreboard called `objectivename`, which tracks `tracking`. This will be a string with regular vanilla trackers (air, dummy, kill counts, etc...)

`remove_objective(objectivename)`no explanations needed

`set_display(objective,where)` if `objective` is null, will clear the display slot
