### ISSUE TITLE
Add import / export

### ISSUE THREAD

**Issue by Flutterish** [gnembon/scarpet#59]
It is currently not possible to import functionality from one app to another.
I suggest a node.js-esque solution:
```
// in myFirstApp.cs
app : 'exports' = m(
    l( 'A', _( a, b ) -> functionA( a, b ) ),
    l( 'B', _( a, b ) -> functionB( a, b ) )
);
// or
export(
   m(...)
);
```
and
```
// in mySecondApp.cs
firstApp = import( 'myFirstApp.cs' ); // reference to app : 'exports' from myFirstApp.cs
```
While it is possible to `run( 'script load myFirstApp' );`, its not really possible to retreive values in a non-hacky way.

**Comment by gnembon** [comment]
I actually added import() function to 1.3.3 carpet, but its not yet where I wanted to be. Right now it imports the entire content of another app (all global functions and variables), but that's currently the only way to ensure they all can run. That might be tweaked before full 
1.7 scarpet

**Comment by gnembon** [comment]
added 1.3.4
