### ISSUE TITLE
Can't supply arguments to __command()?

### ISSUE THREAD

**Issue by nupanick** [gnembon/scarpet#66]
if I define an app like this:

```
//hello.sc
__command(who) -> print('Hello, ' + who + '!');
```

I would expect to be able to call it in-game as `/hello 'world'`. But I actually get the error message, `Incorrect argument for command`.

According to the documentation, if `__command()` is defined, then it also defines all other global commands as sub-commands, so I assume that scarpet is looking for a sub-command called "world". But there are no sub-commands in this file, so I'd expect the "world" string to instead get passed to the __command() method. Is there a way to do this, or can the "root command" not accept arguments?

**Comment by indoorjetpacks** [comment]
If I understand correctly, it defines public functions, not global ones. 

>...register all public (no underscore) functions available in the module as subcommands
 So ones that start with an underscore wouldn't be loaded for use. So if you added something like this:`test_me(bar) -> print('foo ' + bar);` after that, then you could call it after loading hello.sc by doing `/hello test_me [someargument]

What would the benefit be of trying to pass arguments to the __command() method as opposed to using other functions inside of the script?

**Comment by nupanick** [comment]
The use case is defining a single-command 'app'. Currently, you can do this, but only if that single command takes zero arguments. I'd like to be able to define a single-command app tha

**Comment by Nameless-123** [comment]
Unfortnuately, it's not possible right now

**Comment by gnembon** [comment]
as @Nameless-123  is saying - the idea is that a command is just a selection of 'actions' like in this case:
https://github.com/gnembon/fabric-carpet/blob/021befbd3c484d9e81b3206f9ec65598f018a0b6/src/main/resources/assets/carpet/scripts/overlay.sc#L27

However I recognize the needs for simpler apps to only use `__command` as their only interface, and that's something that will be added soon.

**Comment by gnembon** [comment]
scarpet has now full support for all important arguments types as well as custom commands
