### ISSUE TITLE
Running material() on wood blocks returns as wool

### ISSUE THREAD

**Issue by indoorjetpacks** [gnembon/scarpet#75]
Checked in carpet 1.3.6 and 1.3.7, running material() on a block that should be wood (i.e., oak log, stripped spruce log, birch planks, etc) will return as _wool_ instead of the expected _wood_. As far as I can tell, happens with all variants of logs and planks, both normal and stripped. Didn't test with slabs/stairs though.

Can test by placing any wood one block northward of the player and running:
`/script run print(material(pos_offset(pos(player()),'north')))`

**Comment by gnembon** [comment]
weird, sounds like a typo to me. Will fix
