### ISSUE TITLE
[suggestion]add "__on_player_respawn(player)"

### ISSUE THREAD

**Issue by Neubulae** [gnembon/scarpet#86]
or maybe some others like "__on_player_spawn(player)" which fires when a player spawns in(joining the world) or respawns

**Comment by Ghoulboy78** [comment]
__on_player_respawns is unnecessary as you can just do `entity_event(player,'on_death')` to a similar effect, though i guess __on_player_spawns is a good idea

**Comment by Neubulae** [comment]
> __on_player_respawns is unnecessary as you can just do `entity_event(player,'on_death')` to a similar effect, though i guess __on_player_spawns is a good idea

Not quite, the thing I want to process has to run when a player respawns, not dies, tho setting up a delay could be feasible…

**Comment by Ghoulboy78** [comment]
then make it `spawns` , not `respawns`, if youre also gonna make it when they join back in the world
(also cos its two letters less for me to type :P)

**Comment by Neubulae** [comment]
> then make it `spawns` , not `respawns`, if youre also gonna make it when they join back in the world
> (also cos its two letters less for me to type :P)

 I guess it's fine

**Comment by Ghoulboy78** [comment]
I thinks it's already been added @Neubulae

**Comment by Neubulae** [comment]
> I thinks it's already been added @Neubulae

I saw it, I guess that's for bed/anchor or things
